mholt/PapaParse

papaparse.js
tests/test-cases.js
tests/test-runner.js
tests/tests.css

I'm not positive this is correct, but it feels like an improvement to me, and it passes the tests.

more refactoring: StringStreamer

---

papaparse.js

Added functionality to return Papa obj if app is using require.

Making Papa require friendly.

---

papaparse.js

This PR was created based on this commit b3c84bf1f1a0781e5d30fe91e44c9e23699c362b. Take a look at this and let me know if you see something wrong.

Issue#8 Fix complete results with partial results

---

papaparse.js
tests/test-cases.js

handle empty quoted field at EOF

---

papaparse.js
tests/test-cases.js

Using PapaParse inside a worker

---

papaparse.js

if preview didn't find a row, avgFieldCount will be NaN or Infinity

avoid division by zero

---

papaparse.js

symetric parse and unparse

---

papaparse.js

fixes https://github.com/mholt/PapaParse/issues/337

char replacement if non default quoteChar

---

papaparse.js
tests/test-cases.js

For unparse: use the header: option to specify whether a header should be printed or not.

[unparse] header-option.

---

docs.html

when using a collection of data objects
See #246

Document how header row is populated

---

README.md
papaparse.js
tests/node-tests.js

Adds support for parsing Node streams.

Node support

---

papaparse.js

Fixes #374
As discussed in issue, tests for NetworkStream require additional infrastructure to be addressed in a new issue.
I could not find any documentation about whether the minified file should be generated in this commit or if there is another process for that. Please advise.

Add support for download xhr headers

---

papaparse.js

It's very nice to have the JavaScript library say what its license is. I copied Angular's approach for this pull request.

Including license statement

---

docs.html

This commit adds documentation for the custom escape character option to the gh-pages branch.

Added documentation for the escapeChar (#459)

---

papaparse.js
tests/node-tests.js
tests/test-cases.js

This is a reworking of #166. That PR is pretty old, but there seemed to be consensus that while it wasn't perfect, it was perhaps good enough to merge.

Fix pause/abort/resume in streaming mode

---

player/player.js

Added header to config in unparse in player.js.

player.js unparse header included in config

---

papaparse.js
tests/node-tests.js
tests/verylong-sample.csv

Add test and long enough csv file to need more than one chunk to process

Add row counter for chunked parsing for accurate row reporting on errors

---

resources/js/lovers.js

Added CircleHD user of Papa

---

package.json
tests/tests.html

Adding chai as an npm devDependency

---

docs/resources/css/common.css

Bumping font size and darkening color on h5, footer h4

Bumping font size and darkening color on h5, footer h4

---

papaparse.js

Resolves https://github.com/mholt/PapaParse/issues/235

Object.prototype.toString instead of instanceOf to determine arrayness

---

papaparse.js
tests/test-cases.js

This fixes the behaviour discussed on #495 
As it's an api change it should be released on a new major version. 
Any feedback will be much appreciated.

Return unique row as data on step function

---

papaparse.js
tests/test-cases.js

Consistently apply regex escaping to quoteChar

---

papaparse.js
tests/test-cases.js

Adds tests and fixes an issue that incorrectly parses the headers with step functions

Fixes #619

---

resources/js/lovers.js

I just realized we never added Flatfile here!

Adding flatfile.io to lovers.js

---

docs/resources/js/lovers.js

Papa Parser is a great help for us. Such a function like guessing delimiters saved lots of our clients time.

Add mailcheck.co to lovers.js

---

papaparse.js
tests/node-tests.js
tests/test-cases.js

WIP: BugFix #636 Pause and resume (In a quick succession) gets you lot of exceptions and an infinite loop
So my plan is to have a logic of this kind for all the Streamers (Since ChunkStreamer is common in all), what do you feel about it? Any different ideas?

BugFix #636 Pause and resume (In a quick succession) gets you lot of exceptions and an infinite loop

---

docs.html

add the documentation about the feature introduced by this PR: https://github.com/mholt/PapaParse/pull/375/files

Add downloadRequestHeaders Doc to the website

---

resources/js/lovers.js

Familio uses Papa and absolutely loves it

Include Familio

---

docs/faq.html

Since several users have reported an error when setting worker:true, update FAQ with reference to issue #655.

Update FAQ with reference to configuration issue #655

---

papaparse.js
tests/test-cases.js

PR for https://github.com/mholt/PapaParse/issues/658

Handle delimiter guessing, when not all of the fields are quoted

---

docs/docs.html

Might want to [check the rest of the docs](https://github.com/mholt/PapaParse/issues/668); I only changed 1 character ;)
But looking at the file history, seems you kept it up.

fix  #668, update webiste to v5

---

docs/resources/js/lovers.js

Unclosed braces cause JS error on https://www.papaparse.com/

Fix syntax error in lovers.js

---

papaparse.js
tests/test-cases.js

This resolves the issue mentioned in #685

Bugfix: Resolve parsing issue when first field is empty and unquoted

---

papaparse.js
tests/test-cases.js

Fix  misplaced quotes parsing (#699)

---

papaparse.js
tests/test-cases.js

Fixes https://github.com/mholt/PapaParse/issues/672#issuecomment-522758754

Fix step callback function when skipping empty lines (#672)

---

papaparse.js

Just corrects a minor spelling mistake.

Correct small typo

---

papaparse.js

Saw you used Object.keys elsewhere so I thought it would be fine to use it directly instead

Removed unncessary utility fn

---

papaparse.js

Drop redundant getNextUnquotedDelimiter function

---

docs/resources/js/lovers.js

We're big fans of Papa here at Retool. We use it internally and expose the library to all our users when they write JS in app.

Add Retool to PapaParse lovers list

---

papaparse.js
tests/test-cases.js

Update ISO_DATE regex to match full string

---

papaparse.js
tests/test-cases.js

fix: columns config works with input type object

---

docs/resources/js/lovers.js

Love what you're doing! Thank you for your incredible work

new testimony

---

docs/faq.html

fixed missing space after readme link

Update faq.html - missing space

---

papaparse.js
tests/test-cases.js

Hopefully this is the right way to fix this, I'm not very familiar with this codebase so please advise :) .
fixes #1085

Only attempt to parse headers once
