papaparse.js
tests/node-tests.js
tests/test.js

Further to discussions in #167, this PR adds support for loading PapaParse as a module. It adds basic automated tests for loading as a node js module (although some options will not work eg remote file parsing, web workers etc). It also adds support for loading via RequireJS (untested) and WebPack (manually tested). Finally, it stops PapaParse from being added into the global context (ie window) when loaded as a module.

Module loading

---

papaparse.js
tests/test-cases.js

This restores the unchunked read previously present in https://github.com/mholt/PapaParse/commit/57a7349c41502afff0328bab918d0e10f8b8fd80#commitcomment-10179215 .

read files in a single chunk for complete results (#179)

---

papaparse.js
tests/test-cases.js

I was using PapaParse to parse through a large CSV file recently, and wanted to make use of the ParseHandle's abort method. However, despite calling abort(), the parser continued to run. Following the pattern for pausing the parser, I attempted to flesh out support for calling abort. From what I could tell, there just wasn't a variable in place for abort() like there is for pause(). 
The original test case seemed to pass regardless of whether or not abort() was working, because the string provided was being parsed in a single go. Hence, the callback was only called once no matter what. I included the chunkSize on the config to make the test parse the string in pieces. Now, the test does indeed fail when abort() is not working, and passes when it does work.
Feedback is welcome.

fixed support for aborting parsing

---

index.html

As it says, file parsing happens asynchronously, so there is no need to safe to the results variable.

Removed result variable for file parsing.

---

docs.html
faq.html

I read the docs thoroughly but missed the note in the middle of the FAQ about concatenating Papa Parse with other libraries. This adds that (pretty significant) caveat to the `config.worker` description and the Multi-Threading (Workers) FAQ since concatenating JS for production is pretty standard these days.

More visible explanation of concatinating issue (#163) in the docs

---

papaparse.js

Some IDEs (i.e. IntelliJ/WebStorm) are able to extract and show them.

Replace plain comments with JSDoc comments

---

papaparse.js

In function guessDelimiter always used '\n' as newline. This pull request fix it.

Fix newline option for delimiter autodetect

---

papaparse.js
tests/test-cases.js

This stems from a production issue we faced while using PapaParse.  Customers had uploaded data with mixed line endings (likely due to a concat from different systems).  We were most interested in extracting header info, so this fix was better than the current guessing mechanism.  Still room for improvement.

Fixes auto detecting mixed line endings

---

papaparse.js

Fix the "complete(res, file)" for parse(file, ...) so that "file" is not undefined in "complete". Works for the tested case, but it is not clear if this might cause problems with other "Streamed" reading modes.

Fix for complete(res, file) in parse(file, ...)

---

papaparse.js
tests/test-cases.js

Note: Some characters like * or ^ don't work properly as custom quote character.
Kindly check the [demo](http://prayashm.github.io/PapaParse/demo)
#218

Add custom quote character option for parsing CSV files

---

papaparse.js
tests/test-cases.js

This PR allows for explicitly defining which columns you'd like to apply dynamic type coercion to. See added tests for all supported use-cases. Here's a basic example:
```js
let csv = `code,price
0001,1.25
0234,5.65`;
Papa.parse(csv, {
header: true,
dynamicTypings: {
price: true
}
})
// -> [ { code: "0001", price: 1.25 }, { code: "0234", price: 5.65 } ]
```

Support dynamic typing on explicitly defined columns

---

papaparse.js
tests/test-cases.js

I noticed there are some difficulties with auto-detecting delimiters (best described at https://github.com/mholt/PapaParse/issues/153 & https://github.com/mholt/PapaParse/issues/290).
I've faced similar issues, but I can't follow the suggestion of specifying the delimiter every time, because I don't know it before parsing the file.
However I do, in my case, have a good idea of what structure the data will be in - for example I always expect the first cell to be empty (and can handle the errors arising from that ever not being true).
This lead me to the idea of allowing a callback to be used to determine the delimiter, based on the parsed file content (before it is parsed to CSV). This lets me simply return the first character of the input to specify the delimiter, rather than having to …

Add callback option for specifying delimiter.

---

papaparse.js
tests/test-cases.js

Allows specifying the quoteChar in config for unparse like:
``` javascript
Papa.unparse(data, {
quoteChar: "'"
})
```

Add custom quote character to unparse

---

papaparse.js

I'd like to show the part of the data when there is no Content-Range header. This usually solves the case with gzip-compression and smaller file size.

No Content-Range, then finish with current data!

---

papaparse.js

This is makes PapaParse useable in sites where Content Security Policy is used.
Closes #363

Determine global scope without using eval

---

papaparse.js

resolves #391, tested with chrome (59.0.3051.3), safari (10.0.2), electron (1.6.10), Legacy node (0.12.14), LTS node (6.10.3) and current node (8.0.0)

Better recognition of node commonJS

---

papaparse.js
tests/test-cases.js

Parsing was broken with newline-terminated short data with `delimiter: auto` and `skipEmptyLines: true`, as described in #309.
Test added in first commit, failed with the following error:
Second commit fixes the bug and passes the test.

Skip correctly empty lines while detecting delimiter, fixes #309

---

README.md

I tested on a much later version of Node in a previous PR, which lead to
an embarassing failing test on CI. ;)

Note about testing with the right Node version

---

papaparse.js
tests/test-cases.js

This pull request adds the optional configuration option `escapeChar` to escape the `quoteChar` in a quoted field. This option allows to parse CSV files where a non-standard escape character is used. (p.E. `\"` instead of `""`) .
If `escapeChar` is provided, it may contain a one character long string.
If `escapeChar` is not provided, the `quoteChar` will be used as fallback.
The `escapeChar` must appear before the `quoteChar`.
Two tests have been added to validate the functionality of this feature.
Solves issue #459.

Add option to configure escape character (#459)

---

.travis.yml
README.md

Node.js version 0.12 reached end-of-life on 2016-12-31.
See https://github.com/mholt/PapaParse/pull/477#issuecomment-379861967 for context.

Remove support for node 0.12

---

papaparse.js
tests/node-tests.js

Fixes #472 
There don't seem to be any existing tests that verify the `error` callback, so I added some.

Pass full error object on stream errors

---

papaparse.js
tests/node-tests.js

I discovered this bug when trying to process and upload 1.3 million csv records to an elasticsearch instance.  The csv reader was parsing data into my queue faster than I could upload the data in my datastore and thus the process memory would crash node.  I implemented a pausing system so that the upload queue wouldn't get overloaded but then I noticed that the parser would call `complete` before the entire csv had been processed.  This fix allows for the pause/resume to work correctly when they are triggered in an async fashion.

Fix async pause/resume with ReadableStreamStreamer

---

papaparse.js
tests/test-cases.js

Allow developers to trim leading/trailing spaces from headers. Our sample CSV looked like:
"name, duration, due"

Optionally trim whitespace from headers

---

papaparse.js

"typeof null" return "object". the copy() function has been updated to copy null correctly whereas before, null was being converted to {}. this update is important for the transform function PR that I'm going make.

copy function will copy null primitive correctly now

---

papaparse.js
tests/test-cases.js

This PR addresses the issue: "Skip comments for delimiter detection #489".
The guessDelimiter function now takes the comments config and that seems to fix the problem of it failing when there are 10 or more lines of comments at the beginning of CSV.

When guessing a delimiter, lines with comments are ignored now

---

.eslintrc.js
README.md
papaparse.js
tests/node-tests.js

This may be a controversial PR and as such I fully expect good feedback and discussion.  That being said, I believe that this is a very useful PR that allows CSV processing on extremely large files to be done much easier.   The node stream API is very good at what it does and so I wanted to take advantage of that.
I had a use case (for which I mentioned in my previous PR) to take a CSV file with 1.6 million entries (145.5MB) and upload each entry to an elasticsearch service.  Before this feature, I had to implement a queue system that would pause the parser when overloaded and resume the parser when empty.  It's not complicated code but it can be tricky to get right.  With this feature in place, I could get rid of all that code and replace it with the following:
``` …
```

Add node-style streaming support

---

.travis.yml

v4 reached end of life on 2018-04-30. v10 was released recently.
v9 will reach end of life in June, but we can keep it for now.

Drop Node v4 and add v10

---

papaparse.js
tests/test-cases.js

This PR addresses issue: "dynamicTyping should use JSON.parse and config should allow custom processing #487"
The config can now take the key 'transform' with a function value. That function can apply transformations to the values in a CSV.
This allows the use of the JSON.parse() functionality I discussed without affecting the current dynamicTyping option.

Add config option that applies custom function to values

---

papaparse.js
tests/test-cases.js
tests/test.js

Scope
=====
This updates the serialization code to allow multi-character delimiters.
I want to present the values in a more human readable format with `, ` as delimiter so that the lines will be `1, 2, 3` instead of `1,2,3`
Changes
========
Update the validation to not enforce single characters, but to still filter against invalid characters.
In this way there is no regression and all previous tests pass.
I added a new test to showcase this functionality
As a drive-by fix, I have updated the phantomjs test runner to propagate the exit code
as it was always exiting with 0 even on errors see https://travis-ci.org/mholt/PapaParse/jobs/389825011#L1418
----------
Once this is accepted the documentation needs to be updated at https://github.com/mholt/PapaParse/blob/gh-pages/docs.html#L256
to …

Allow multi-characters delimiter at serialization.

---

papaparse.js
tests/test-cases.js

Supersedes https://github.com/mholt/PapaParse/pull/449 with improved regex and added tests.
Resolves #252 
Resolves #457
Resolves #535 
Test-driven correction for bugs regarding linebreaks in quoted header fields that are not the same time as the linebreaks between rows. I was able to mostly fix it using an improved regex (using `[^]*?` instead of `.*?` for replacing across newlines).

Fix linebreak problem in headers

---

docs/demo.html
docs/docs.html
docs/resources/js/demo.js
papaparse.js
tests/test-cases.js

Added a boolean config value `skipNoContentLines` which skips lines that only contain delimiters, quotes, and whitespace, instead of just lines that evaluate to an empty string. Works if set alongside `skipEmptyLines` or on its own. Passing tests are included.

New feature: Option to skip lines with no content

---

papaparse.js
tests/test-cases.js

Added support for skipEmptyLines in unparsing using both `true` and `'greedy'` values.
Resolves #553

Use 'greedy' skipEmptyLines in unparse

---

papaparse.js
tests/test-cases.js

Resolves https://github.com/mholt/PapaParse/issues/558
See also:
* [#553 (comment)](https://github.com/mholt/PapaParse/issues/553#issuecomment-413287866)
* #554

Fixes unparsing using 'skipEmptyLines' = 'greedy' when using headers

---

.eslintrc.js
papaparse.js

Unlike strings, Error objects allow you to get stack traces. Also, a lot of libraries will complain if they encounter a thrown non-Error object.
This is in line with standard Javascript best practices. Per https://eslint.org/docs/rules/no-throw-literal:
> It is considered good practice to only throw the Error object itself or an object using the Error object as base objects for user-defined exceptions. The fundamental benefit of Error objects is that they automatically keep track of where they were built and originated.

Throw Error objects instead of strings

---

docs/docs.html

This adds a dedicated section/block for the unparse config option.
I think this way it is more similar to the parse config.
It also clarifies some unparse options (e.g. `quotes` can be an array of booleans).

add table for unparse config options

---

docs/docs.html
papaparse.js
tests/test-cases.js

Introduces a new `unparse` option `columns` to specify the columns/keys manually.
Some points i'm not sure about:
- Default value is currently null 
I think `[]` is not a good choice because then we need to check `_columns.length > 0` in order to know if the user specified a custom value. If someone des a `array.map()` for the keys that results into `[]` then the keys of the first object are used (which is unexpected).
However, maybe `null` looks a bit strange as default value
- I'm not sure about the last test... is the expected value correct?

Fixes issue #609

---

docs/docs.html
papaparse.js
tests/test-cases.js

This was requested/referenced in #620 (docs only) - this PR adds support for `escapeChar` to be used in `unparse`

add ability to support escapeChar on unparse

---

docs/docs.html

add the documentation about the feature introduced by this PR: https://github.com/mholt/PapaParse/pull/375/files
Notes:
- https://github.com/mholt/PapaParse/pull/646
@pokoli  We should delete the gh-pages since it's misleading and the branch is inactive

Add downloadRequestHeaders Doc to the website

---

docs/index.html

https://www.papaparse.com/ currently has 404 link to lovers.js, let's fix it.

Fix invalid link to lovers.js

---

papaparse.js
tests/test-cases.js

question: function return different cause the version change
input:"a,b,c
a,b,c|d|e|f"
output:[["a", "b", "c"], ["a", "b", "c|d|e|f"]] in v4
[["a,b,c"],["a,b,c","d","e","f",]] in v5
expect :[["a", "b", "c"], ["a", "b", "c|d|e|f"]]
resolve:  delta should  record the difference between line which mean smaller is better, when delta is equal, we should compare the avgfieldcount and choose the biggest one.by the way the issue592 can resolve right array use this function.

Modified the GuessDelimiter function

---

docs/docs.html
papaparse.js
tests/test-cases.js

Issues like #692 occur when numbers pass the regex for being numerical, but then are too large to have their precision maintained when using `parseFloat`. To avoid needing to use a library like Big to handle numbers of this size (IMO its a lot of overhead) we instead leave them as strings, and instead would encourage users to use a custom dynamicTyping function if they need to handle them as numbers.

Leave big numbers as strings (>2^53 || <-2^53)

---

papaparse.js

Per MDN.
> Warning: Although String.prototype.substr(…) is not strictly deprecated (as in "removed from the Web standards"), it is considered a legacy function and should be avoided when possible. It is not part of the core JavaScript language and may be removed in the future. If at all possible, use the substring() method instead.

Refactor substr calls to substring calls.

---

papaparse.js
tests/test-cases.js

1) JSON does not guarantee the ordering that fields are encoded in the string, making it unreliable for generic hashing.
2) When ordering is maintained, the strings match the ordering the fields were added to the object, making the unit test too tighly coupled to the order they are added in the implementation.
3) A field whose value is undefined versus not being present presents a difference that deepEqual should assert.  If it does not matter then possibly a different assert should be used.

Address deepEqual using compare by JSON strings.

---

papaparse.js
tests/test-cases.js

update delimiter and newline index if they are earlier than the current position before tested.

#727 fix stale indexes used in whitespace tests during quote parsing.

---

papaparse.js

This should be `self.resume` instead of `this.resume` as `this` refers to the `window` object when the callback occurs. Meaning, it would fail to do the next recursive call if the need arose.
Do you have any testing strategy in mind for such a thing? Do we need a test here?

Using self instead of this to preserve binding.

---

docs/docs.html
papaparse.js

Hi awesome library and first time to contribute to any github project.
I just wanted to  share a little bit of code change to support POST method when the download property of config is true. 
I wanted to share a solution to a problem related to mine in stackoverflow(https://stackoverflow.com/questions/55841129/how-to-using-post-method-to-download-csv-file-using-papaparse) as well as issue #657 
Sorry I did not create any test case for this as I didn't know how I can test a POST method using the available packages, but if you have an advice on how to do it I'll gladly learn it and create one.

Added feature to support POST method when download is true

---

papaparse.js

Avoid ReDOS on float dynamic typing

---

tests/test-cases.js

Tests for #685.
I was not able to reproduce the issue but a test is always better to have.
I also checked the proposed failing cases on [https://www.papaparse.com/demo](https://www.papaparse.com/demo) and they are parsed as expected.
I am using PapaParse for a long time now and I would like to help taking this 109 issues down :).

add test to check for empty field in the begining

---

docs/docs.html
papaparse.js
tests/test-cases.js

Implement escapeFormulae option

---

papaparse.js

When transforming headers, knowing what column index a header refers to can be extremely useful.
This PR adds the header index as an optional second argument to the `transformHeader` config function.
This PR also corrects the `addHeder` typo (changed to `addHeader`).
Cheers!
🤓👍

Add index argument to "transformHeader" config function

---

docs/docs.html

chunkSize documented

---

docs/docs.html

This fixes issue #858
Some people might get confused and think that `quotes: true` will force all fields to be quoted. Actually, this is not the case as `undefined`, `null` and `date-object` values are never quoted.
Also `escapeFormulae` can also prevent the field to get quoted.
I'm unsure about the `date-object` wording, maybe `date-instances` is better?

updated unparse config docs and noted that quote option is ignored for some values

---

docs/docs.html
papaparse.js
tests/test-cases.js

Fixes issue #866. I've also added some test for unparsing multi character delimiter where a field contains the delimiter (and needs to be quoted)

Fix #866 - Multi-character delimiter with quoted field issue

---

docs/docs.html
papaparse.js
tests/test-cases.js

See #796 #793
@pokoli @wcerfgba Hey guys, could you check this PR?
It adds more cases for `escapeFormulae` option, cf https://owasp.org/www-community/attacks/CSV_Injection

Add more cases to escapeFormulae, allow to pass RegExp

---

papaparse.js

fix: set empty string to config.quotechar when it's value is null

---

papaparse.js
tests/test-cases.js

This change should address the performance issue [#911](https://github.com/mholt/PapaParse/issues/911) where parsing a file with a lot of empty rows takes more time than expected when `skipEmptyLines` option is set to `greedy`.

Fix for issue #911

---

papaparse.js
tests/.eslintrc.js
tests/test-cases.js

This fixes #788
Previously, the assumption was if we're in a web-worker AND the worker was loaded from a blob, the worker *must* be ours.

[GH-788] Made the check to determine whether the current web-worker is owned by PapaParse more reliable

---

papaparse.js

Otherwise e.g. `'whatever 0000-00-00T00:00:00Z foo bar'` passed, which was likely unintended.

fix: correct anchoring in iso-date regex

---

.eslintrc.js
papaparse.js

The current implementation used to rely on an instance of `Array` and on its `includes` method. Depending on how many headers one may have to export in the CSV this `Array` can contain many entries and performings `includes` on it might be costly as it grows (most of the cases will have to iterate over the whole collection as duplicates is rather the exception than the rule).
The current PR proposes to rely on a native Set (when available) or a simple polyfill for it. (Side note: I did not know how to put tests on the polyfill as the class is internal and never exposed so I tested it manually on my side)
Related to https://github.com/mholt/PapaParse/commit/970c1dbaab0232c8d056ce1e58dbdcb5347e2206
Please feel free to close this PR if it does not make sense for the project. And thanks a lot …

Fast headerMap to find duplicated headers

---

docs/docs.html
papaparse.js
tests/node-tests.js
tests/test-cases.js

Following #988 , the PR is ready for review.
This PR includes:
Added `Parser.meta` field called `renamedHeaders`.
- The value is `null` if the config is headless, or no renamed headers.
- The value is `Record<string, string>`, in which the keys are the renamed headers and the corresponding values are their original headers, or transformed headers.
The relevant unit tests are updated. I didn't assert all `meta` in existing unit tests by using `assert.deepEqual`. Instead, I used `assert.deepNestedInclude` to assert the values `renamedHeaders` are correct to avoid a monster PR.

feat: renamed headers meta

---

papaparse.js
tests/test-cases.js

We have some helper methods on our Array object.  Papaparse started blowing up with the latest update (seems to be from [this commit](https://github.com/mholt/PapaParse/commit/c1cbe16636be146f5f1d321cdd7cbddc9143b045)).
This bugfix updates the for loop to only interate over the array's elements, not the properties of the Array object.
Here's my testing sandbox, if you want to have a play: https://codesandbox.io/s/zealous-liskov-nuj41l?file=/src/index.js
I don't contribute to OSS often so this is quite new to me.  I'm happy to take any feedback on my pull.

Fix for polluted Array

---

papaparse.js
tests/test-cases.js

When processing duplicate headers with header auto, the position of meta.cursor will be returned as the position of cursor including renamed headers such as _<number>. But it's different from the cursor of the actual file. So set the cursor to the length of the original header.

Fixed cursor when duplicated header

---

papaparse.js

When parsing the config with a boolean value of `escapeFormulae`, the presence of the `escapeFormulae` key is checked but the value itself is not checked.
This means that `_config = {escapeFormulae: false}` behaves the same as `_config = {escapeFormulae: true}`.
[Codesandbox example](https://codesandbox.io/s/competent-goldberg-82vcqn?file=/src/App.tsx)
```ts
import "./styles.css";
import Papa from "papaparse";
export default function App() {
const data = [
["a", "b"],
[1, "=1+2"]
];
const emptyConfigResult = Papa.unparse(data, {});
const escapeFormulaeFalseResult = Papa.unparse(data, {
escapeFormulae: false
});
const escapeFormulaeTrueResult = Papa.unparse(data, { escapeFormulae: true });
return (
<div className="App">
<h3>Empty config</h3>
<pre>{emptyConfigResult}</pre> …
```

fix: check _config.escapeFormulae is true

---

docs/docs.html
papaparse.js
player/player.html
player/player.js
tests/test-cases.js

In this feature enhancement, Added the capability to skip a defined number of lines when converting a CSV (Comma-Separated Values) file to JSON format. This functionality offers users more flexibility when dealing with CSV files with header information or metadata at the beginning, allowing for a more efficient and precise conversion process.
1. Introduced a new configuration parameter, skipFirstNLines, which allows users to specify the number of lines to skip at the beginning of the CSV file during the conversion to JSON. This parameter supports values from 0 and above.
2. Implemented validation for the skipFirstNLines configuration parameter to ensure that it does not negatively impact the parsing process, even if it is set to 0 or given a negative value.
3. Enhanced the user interface …

Skip lines future (Feature Suggestion) #738

---

docs/resources/js/papaparse.js
papaparse.js
tests/test-cases.js

Only skip first n lines in the first chunk and don't take the first line as header (#1045)

---

papaparse.js
tests/test-cases.js

I refactored the header renaming logic to adress #1052, #1007
and updated test to match the improved renaming logic.

Refactor header renaming logic to adress #1052, #1007

---

papaparse.js
tests/test-cases.js

Using `__proto__` as a header name and repeating it can cause an infinite loop due to incorrect counting. This issue can be resolved by replacing {} with an object that has no prototype.

Fix header name counting issue

---

papaparse.js
tests/test-cases.js

Addresses #372, stripping BOM from column keys when parsing the header.
The problem: The first column key includes the invisible BOM character if it exists in the CSV.
Pull request #961 handled BOM stripping for parsing the CSV without keyed data. However, with `header: true` the issue still persisted. This is solved by this pull request that runs the `stripBom` function from #961 also on the header field, before 'transformHeader'.
Also, I added tests for BOM handling.

Strip BOM character from column keys when parsing header, add BOM tests

---

docs/docs.html

Adding this to the documentation so that it can be added to the definitely typed definition, as documentation indicates that it is a stable property.

Mention BYTE_ORDER_MARK in documentation

---

README.md

as one gets a warning now in chrome when opening a HTTP-only link
switch to HTTPS links.
as https://papaparse.com/ doesn't appear to have a valid cert
but https://www.papaparse.com/ does, immediately link there o7

Update README.md: HTTP => HTTPS
